{% set name = "pyrad_mch" %}
{% set version = "0.6.6" %}
{% set sha256 = "89df68646e3a3b40e7e4526b44b2959c13696fe75582054392185cf49d8c9d86" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py2k or win]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - numpy

  run:
    - python
    - pyart_mch

test:
  imports:
    - pyrad

about:
  home: https://github.com/MeteoSwiss/pyrad
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MeteoSwiss Pyrad, Python tool for radar data processing.
  description: |
    This is the MeteoSwiss Pyrad. Pyrad is an open source Python
    module for weather radar data processing. The module controls the
    data flow. The inputs and outputs are specified using config files.
    Most of the core data processing is performed using the MeteoSwiss version
    of Py-ART, originally developed in the framework of the
    Atmospheric Radiation Measurement (ARM) Climate Research Facility for
    working with data from a number of precipitation and cloud radars. The
    MeteoSwiss version of Py-ART contains enhanced
    and experimental functionality. MeteoSwiss regularly contributes back to
    the ARM-DOE Py-ART.
  doc_url: https://pyrad-mch.readthedocs.io/en/stable/
  dev_url: https://github.com/MeteoSwiss/pyrad

extra:
  recipe-maintainers:
    - meteoswiss-mdr
    - Wolfidan
